### ISSUE TITLE
CI pipeline doesn't handle no test results runs

### ISSUE THREAD

**Issue by Victoremepunto** [RedHatInsights/clowder#421]
I observed the CI pipeline is failing on #420  , which tackles a small error in the README, which I presume doesn't run any tests as no code changes where made on it. However checking the CI logs it seems the system expects some sort of test result regardless, making the PR validation to fail.

**Comment by bsquizz** [comment]
I saw another doc change pass the PR checks so not sure, I am re-running the tests on that PR now.

It definitely is inefficient to run the full test suite just for a doc change though :)

**Comment by psav** [comment]
Yeh - we need to have better detection here for when to run the tests @Victoremepunto - want to take a stab at this?

**Comment by Victoremepunto** [comment]
me likes - gonna track and plan to do it yup
