### ISSUE TITLE
Broken links in Getting Started doc page

### ISSUE THREAD

**Issue by Fynardo** [RedHatInsights/clowder#579]
I found what I think are a few broken links in the [getting started page](https://github.com/RedHatInsights/clowder/blob/master/docs/antora/modules/usage/pages/getting-started.adoc).

I tried to investigate where these links should point in order to try and help fix them, as follows:

- In [Install clowder in your local box](https://github.com/RedHatInsights/clowder/blob/master/docs/antora/modules/usage/pages/getting-started.adoc#install-clowder-on-your-local-box) section there is a link for the [developer guide](https://github.com/RedHatInsights/clowder/blob/master/docs/developer-guide.md) that I think should point here: https://github.com/RedHatInsights/clowder/blob/master/docs/antora/modules/ROOT/pages/developer-guide.adoc
- In [Create your first ClowdEnvironment](https://github.com/RedHatInsights/clowder/blob/master/docs/antora/modules/usage/pages/getting-started.adoc#create-your-first-clowdenvironment) there is a link for the [ephemeral environments getting started](https://clouddot.pages.redhat.com/docs/dev/getting-started/ephemeral/index.html) that I think should point here: https://consoledot.pages.redhat.com/docs/dev/getting-started/ephemeral/index.html
- Also in this section, there is a link pointing to the [default ephemeral template](https://github.com/RedHatInsights/bonfire/blob/master/bonfire/resources/ephemeral-clowdenvironment.yaml) which may point here instead: https://github.com/RedHatInsights/bonfire/blob/master/bonfire/resources/ephemeral-cluster-clowdenvironment.yaml
- In [Create your first ClowdApp](https://github.com/RedHatInsights/clowder/blob/master/docs/antora/modules/usage/pages/getting-started.adoc#create-your-first-clowdapp) section there is a link to [ClowdApps API](https://redhatinsights.github.io/clowder/api_reference.html#k8s-api-cloud-redhat-com-clowder-v2-apis-cloud-redhat-com-v1alpha1-clowdapp) which I think should point here: https://redhatinsights.github.io/clowder/clowder/dev/api_reference.html

Hope this helps

**Comment by psav** [comment]
@gburges Can you fix these links?

**Comment by gburges** [comment]
yeah, i actually have a half done PR about this ;)
