### ISSUE TITLE
The steps to run kube_setup.sh are inaccurate

### ISSUE THREAD

**Issue by mgold1234** [RedHatInsights/clowder#616]
go over Getting Cloweder (at REDME.adoc) step by step: 
the part of installtion Clowder with latest release: 
'Clowder can then be installed by visiting the [latest release](https://github.com/RedHatInsights/clowder/releases/latest) page, copying the link to the manifest, and running something similar to that shown below:'
should locate before running the kube_setup.sh script

the script exist in clowder folder, so you have to install it before

**Comment by psav** [comment]
I'm sorry it's taken so long to get back on this one - can you see if the README better represents what you need now?
