### ISSUE TITLE
docs: broken link to bonfire ephemeral environments

### ISSUE THREAD

**Issue by eliranmal** [RedHatInsights/clowder#812]
the _getting started_ page (at `/docs/antora/modules/usage/pages/getting-started.adoc`) links to a broken reference for working with bonfire, in this stanza:

> Bonfire is a cli tool used to deploy apps into ephemeral environments. Read about getting started with bonfire on ephemeral environments [here](https://consoledot.pages.redhat.com/docs/dev/getting-started/ephemeral/index.html)

that linked page no longer exists, and there doesn't seem to be any equivalent one on the consoledot.pages docs.

looks like it can be safely replaced with [the bonfire repo readme page][1].

other suggestions (which are probably too general for this purpose):
- [IQE testing in ephemeral environments][2] on the redhat engineering docs
- [ephemeral environment and service onboarding][3] on the SMQE wiki redhat-source page

[1]: https://github.com/RedHatInsights/bonfire
[2]: https://docs.engineering.redhat.com/pages/viewpage.action?spaceKey=ENT&title=IQE+Testing+in+Ephemeral+Environments
[3]: https://source.redhat.com/groups/public/smqe/smqe_wiki/ephemeral_environment_and_service_onboarding

**Comment by psav** [comment]
@gburges Can you take a look at this please?

**Comment by eliranmal** [comment]
thank you! 🍪
